MI-2274: AutoComplete Component
Brightscout/mm-ui-library pull request #41
Opened 2022-11-08 15:27 UTC by tanisha-agarwal

### Ticket Link
[MI-2276](https://brightscout.atlassian.net/browse/MI-2276)

### Description
- Created AutoComplete Component
- Removed repetitive code from the Select component
- Removed unnecessary styles from the Tooltip and Spinner component

### Screenshots
![image](https://user-images.githubusercontent.com/102018792/200605036-4735e5d0-f6ed-4536-8915-d6da31ff0ef6.png)
![image](https://user-images.githubusercontent.com/102018792/200605180-15bfd0b5-a501-4c92-b9b7-5624fae19ca6.png)
![image](https://user-images.githubusercontent.com/102018792/200605314-06484dc3-cd12-4302-a89e-bbca24c9cdbb.png)

2022-11-09 05:28 UTC, raghavaggarwal2308 requested changes

2022-11-09 05:28 UTC, raghavaggarwal2308 commented on src/components/AutoComplete/AutoComplete.component.tsx
> +import {List} from '../List/List.component';
can't this be imported as `@Components/List/List.component`? just like you did on line 5-6

2022-11-09 05:28 UTC, raghavaggarwal2308 commented on src/components/AutoComplete/AutoComplete.component.tsx
> +			setOpen(options.length > 0 && !!searchQuery);
Using `!!searchQuery` is same as `searchQuery` right?

2022-11-09 05:28 UTC, raghavaggarwal2308 commented on src/components/AutoComplete/AutoComplete.component.tsx
> +			{options.length > 0 && (
```suggestion
			{options.length && (
```

2022-11-09 05:28 UTC, raghavaggarwal2308 commented on src/components/Input/Input.component.tsx
> +	</StyledFieldSet>
I think the indentation is not right here

2022-11-09 05:28 UTC, raghavaggarwal2308 commented on src/components/Input/Input.component.tsx
> +			event.target.placeholder = type === 'focus' ? '' : inputLabel;
```suggestion
			event.target.placeholder = (type === 'focus') ? '' : inputLabel;
```
Just because it makes the code more readable

2022-11-09 05:28 UTC, raghavaggarwal2308 commented on src/components/Select/Select.component.tsx
> +                placeholder=' '
```suggestion
                placeholder=''
```
maybe? Or we can just skip it?

2022-11-09 06:07 UTC, ayusht2810 commented on src/components/Input/Input.d.ts
> +
fix indentation

2022-11-09 06:07 UTC, ayusht2810 commented on src/components/List/List.styles.ts
> +        // Color of the selected trailing check mark is set to primary color
```suggestion
        // Color of the selected trailing check mark is set to the primary color
```

2022-11-09 06:07 UTC, ayusht2810 commented on src/components/Select/Select.component.tsx
> +        if (e.target === trailingIconRef.current) return;
```suggestion
        if (e.target === inputRef.current || e.target === trailingIconRef.current) return;
```

2022-11-09 06:07 UTC, ayusht2810 commented on src/components/Select/Select.component.tsx
> +                    name={(isOpen || value) ?'Close' : 'ArrowDown'}
```suggestion
                    name={(isOpen || value) ? 'Close' : 'ArrowDown'}
```

2022-11-09 06:07 UTC, ayusht2810 commented on src/components/Select/Select.component.tsx
> +            {options.length > 0 && (
```suggestion
            {options.length && (
```

2022-11-09 06:07 UTC, ayusht2810 commented on src/components/AutoComplete/AutoComplete.d.ts
> +		leadingIcon?: Exclude<IconType, 'Spinner'>;
fix indentation

2022-11-09 17:04 UTC, raghavaggarwal2308 approved these changes

2022-11-09 17:07 UTC, raghavaggarwal2308 approved these changes

2022-11-09 17:07 UTC, raghavaggarwal2308 commented on src/components/Select/Select.component.tsx
> +				placeholder=""
use single quotes for strings. Check everywhere

2022-11-10 10:24 UTC, ayusht2810 approved these changes

2022-11-10 10:24 UTC, ayusht2810 commented on src/components/Select/Select.component.tsx
> +					<Icon name={leadingIcon} size={16} />
```suggestion
					<Icon name={leadingIcon} size={16}/>
```

2022-11-11 10:58 UTC, avas27JTG commented on src/components/AutoComplete/AutoComplete.component.tsx
> + * @returns list of items that included query with the given query
```suggestion
 * @returns list of items that include query with the given query
```

2022-11-11 10:58 UTC, avas27JTG commented on src/components/AutoComplete/AutoComplete.component.tsx
> + * An asynchronous function to search the query in the given list
```suggestion
 * An asynchronous function to search a query in the given list
```

2022-11-11 10:58 UTC, avas27JTG commented on src/components/AutoComplete/AutoComplete.component.tsx
> + * 		{label: 'koko 1', value: 'Value 1'},
```suggestion
 * 		{label: 'label 1', value: 'Value 1'},
```

2022-11-11 10:58 UTC, avas27JTG commented on src/components/AutoComplete/AutoComplete.component.tsx
> + * 		{label: 'asd 2', value: 'Value 2'},
```suggestion
 * 		{label: 'label 2', value: 'Value 2'},
```

2022-11-11 10:58 UTC, avas27JTG commented on src/components/AutoComplete/AutoComplete.component.tsx
> +	};
```suggestion
	const onDropDownCloseHandler = (e: MouseEvent) => e.target !== ref.current && setOpen(false);
```

2022-11-11 10:58 UTC, avas27JTG commented on src/components/AutoComplete/AutoComplete.component.tsx
> +	});
```suggestion
	}, []);
```

never use `useEffect` without a dependency

2022-11-11 10:58 UTC, avas27JTG commented on src/components/Input/Input.component.tsx
> +					<Icon name='Close' size={12} iconColor='#fff'/>
```suggestion
					<Icon name='Close' size={12} iconColor='#ffffff'/>
```

always use hex color code, some browsers create problems

2022-11-11 10:58 UTC, avas27JTG commented on src/components/Input/Input.d.ts
> +	 * Handler triggered on clicking close icon button
```suggestion
	 * Handle trigger on clicking the close icon button
```

2022-11-11 11:24 UTC, avas27JTG approved these changes

2022-11-11 11:25 UTC, merged