[MI-2607] Create reusable null state component
Brightscout/mm-ui-library pull request #55
Opened 2023-01-12 13:21 UTC by SaurabhSharma-884

### Ticket Link
[MI-2607](https://brightscout.atlassian.net/browse/MI-2607)

### Description
Added null state component.

2023-01-13 06:49 UTC, atisheyJain03 requested changes

2023-01-13 06:49 UTC, atisheyJain03 commented on src/components/Nodata/Nodata.component.tsx
> +import React from 'react';
change file name, component name, prop name to NoData, NoDataProps

2023-01-13 06:49 UTC, atisheyJain03 commented on src/components/Nodata/Nodata.styles.ts
> +export const Container = styled.div(() => {
instead of using dot can we do like this  
```
export const Container = styled('div')(() => {

});
```

to maintain consistency

2023-01-20 10:20 UTC, atisheyJain03 requested changes

2023-01-20 10:20 UTC, atisheyJain03 commented on src/components/NoData/NoData.styles.ts
> +    return {
don't use return here

2023-01-20 10:40 UTC, SaurabhSharma-884 commented on src/components/NoData/NoData.styles.ts
> +    return {
not working without return

2023-01-20 10:41 UTC, atisheyJain03 approved these changes

2023-01-20 11:27 UTC, avas27JTG commented on src/components/NoData/NoData.d.ts
> +     * Name of icon to be displayed on component
```suggestion
     * Name of icon to be displayed on the component
```

2023-01-20 11:27 UTC, avas27JTG commented on src/components/NoData/NoData.d.ts
> +     * Text to be displayed as description of no data
```suggestion
     * Text to be displayed as a description of no data
```

2023-01-20 11:27 UTC, avas27JTG commented on src/components/NoData/NoData.component.tsx
> +                    iconColor='#84878F'
create a constant

2023-02-06 14:26 UTC, avas27JTG approved these changes

2023-02-07 05:39 UTC, merged