MI-2601: Create Reusable tab component
Brightscout/mm-ui-library pull request #56
Opened 2023-01-13 11:14 UTC by SaurabhSharma-884

### Ticket Link
[MI-2601](https://brightscout.atlassian.net/browse/MI-2601)

### Description
Added reusable tab component.

2023-01-20 10:34 UTC, atisheyJain03 requested changes

2023-01-20 10:34 UTC, atisheyJain03 commented on src/components/Tabs/Tabs.d.ts
> +
remove extra line

2023-01-20 10:46 UTC, atisheyJain03 approved these changes

2023-02-06 11:22 UTC, avas27JTG approved these changes

2023-02-06 11:22 UTC, avas27JTG commented on src/components/Tabs/Tabs.d.ts
> +     * Have all Tabs proportionately fill all available width.
```suggestion
     * Have all tabs proportionately fill all available widths.
```

2023-02-06 11:22 UTC, avas27JTG commented on src/components/Tabs/Tabs.d.ts
> +     * Have all Tabs evenly fill all available width
```suggestion
     * Have all tabs evenly fill all available widths
```

2023-02-06 13:26 UTC, merged