[MI-2615]: Fixed the placeholder of modal components like Autosuggest, Input field, and Textarea
Brightscout/mm-ui-library pull request #60
Opened 2023-02-03 11:01 UTC by Nityanand13

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/AutoSuggest/index.tsx
> +                </label>}
```suggestion
                {inputValue?.length>0 && (
                    <label className={'margin-0 wt-400 auto-suggest__field-placeholder'}>
                        {placeholder}
                        {required && '*'}
                    </label>
                    )}
```

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/AutoSuggest/index.tsx
> +                {inputValue?.length>0 && <label className={'margin-0 wt-400 auto-suggest__field-placeholder'}>
```suggestion
                {inputValue?.length && <label className={'margin-0 wt-400 auto-suggest__field-placeholder'}>
```

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/AutoSuggest/index.tsx
> +                {inputValue?.length>0 && <label className={'margin-0 wt-400 auto-suggest__field-placeholder'}>
check if this works

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/AutoSuggest/index.tsx
> +                    className={`auto-suggest__input ${disabled && 'cursor-not-allowed'} ${inputValue?.length>0 && 'auto-suggest__input--shifted'}`}
same

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/AutoSuggest/index.tsx
> +                    </label>}
same. fix everywhere

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/AutoSuggest/index.tsx
> +                    <div className={`auto-suggest__selected-option-value text-ellipsis ${inputValue?.length>0 && 'auto-suggest__input--shifted'}`}>{renderValue(selectedOption)}</div>
```suggestion
                    <div className={`auto-suggest__selected-option-value text-ellipsis ${inputValue?.length && 'auto-suggest__input--shifted'}`}>
                       {renderValue(selectedOption)}
                    </div>
```

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/InputField/index.tsx
> +        {value.length>0 && <label className={'wt-400 form-group__field-placeholder'}>
```suggestion
        {value.length>0 && <label className='wt-400 form-group__field-placeholder'>
```

2023-02-03 16:50 UTC, ayusht2810 commented on src/components/InputField/index.tsx
> +        {value.length>0 && <label className={'wt-400 form-group__field-placeholder'}>
fix everywhere

2023-02-03 16:50 UTC, ayusht2810 commented on src/styles/components/_autoSuggest.scss
> +  &__field-placeholder {
```suggestion
  }
  
  &__field-placeholder {
```

2023-02-07 06:07 UTC, ayusht2810 approved these changes

2023-02-07 17:01 UTC, ayusht2810 submitted a review, later dismissed
Update the version of the library.

2023-02-08 09:21 UTC, sooraj-shukla requested changes

2023-02-08 09:21 UTC, sooraj-shukla commented on src/components/AutoSuggest/index.tsx
> +                {!!inputValue?.length && (
Please update the PR description and add screenshots if the UI is updated.

2023-02-08 09:21 UTC, sooraj-shukla commented on src/styles/components/_autoSuggest.scss
> +    @include positioning(absolute, 10px, '', '', 17px, 0);
Include mixins to top.

2023-02-08 09:21 UTC, sooraj-shukla commented on src/styles/components/_textArea.scss
> +    top: 6px;
Can't we give the top using `positioning` mixin.

2023-02-08 09:21 UTC, sooraj-shukla commented on src/styles/components/_textArea.scss
> +    display: block;
Can't we use a util class for this?

2023-02-16 10:09 UTC, sooraj-shukla approved these changes

2023-02-16 10:22 UTC, manojmalik20 approved these changes

2023-02-16 10:38 UTC, merged