[MI:2923]: Create Post Card Component
Brightscout/mm-ui-library pull request #73
Opened 2023-03-23 12:57 UTC by aushwin

2023-03-25 07:18 UTC, sooraj-shukla requested changes

2023-03-25 07:18 UTC, sooraj-shukla commented on src/components/PostCard/subComponents/PostHeader/PostHeader.component.tsx
> + *  floatingMenuComponents={floatingMenuComponents}
```suggestion
 *  floatingMenuComponents={floatingMenuComponents}
 * />
```

2023-03-25 07:18 UTC, sooraj-shukla commented on src/components/PostCard/PostCard.component.tsx
> + * ```
```suggestion
 *  postMessage={postMessage}
 * />
 * ```
```

2023-04-06 07:20 UTC, sooraj-shukla approved these changes

2023-04-06 14:43 UTC, avas27JTG approved these changes

2023-04-06 14:43 UTC, avas27JTG commented on src/components/PostCard/PostCard.stories.tsx
> +	floatingMenuComponents: [<button>Testing</button>, <button>author</button>],
```suggestion
	floatingMenuComponents: [<button>Testing</button>, <button>Author</button>],
```

2023-04-07 04:34 UTC, merged