[MI-2971]: Fix checkbox and add size variants
Brightscout/mm-ui-library pull request #81
Opened 2023-04-06 11:51 UTC by SaurabhSharma-884

### Ticket ID
https://brightscout.atlassian.net/browse/MI-2971

### Description
- Rebuild the checkbox component
- Add size variants for the checkbox

### Screenshot
![Screenshot from 2023-04-06 17-20-00](https://user-images.githubusercontent.com/115625377/230369186-d1498cbc-55b0-4cb5-8856-a63474942eb6.png)
![Screenshot from 2023-04-06 17-20-11](https://user-images.githubusercontent.com/115625377/230369204-91283472-877d-4414-8408-29da656e2a21.png)
![Screenshot from 2023-04-06 17-20-22](https://user-images.githubusercontent.com/115625377/230369210-429be908-e447-4d9d-996c-d36351e55089.png)

2023-04-13 11:16 UTC, raghavaggarwal2308 requested changes

2023-04-13 11:16 UTC, raghavaggarwal2308 commented on src/components/CheckBox/CheckBox.component.tsx
> +
```suggestion
```

2023-04-13 11:16 UTC, raghavaggarwal2308 commented on src/components/CheckBox/CheckBox.styles.ts
> +    // Styles of input checkbox active on checked state
```suggestion
    // Styles of input checkbox active in checked state
```

2023-04-13 11:16 UTC, raghavaggarwal2308 commented on src/components/CheckBox/CheckBox.component.tsx
> +    const {className = '', id, label, error, disabled, size = 'md', ...restProps} = props;
constant for 'md', 'sm' & 'lg'?

2023-04-21 08:04 UTC, raghavaggarwal2308 approved these changes

2023-05-08 08:05 UTC, manojmalik20 commented on src/constants/index.ts
> +const CHECKBOX_SIZE: Record<string, CheckboxSizeTypes> = {
It should be an enum.

2023-05-09 06:50 UTC, manojmalik20 approved these changes

2023-05-10 04:28 UTC, merged